=== aws-cloudformation/community-registry-extensions/resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
{
  "typeName": "AwsCommunity::ApplicationAutoscaling::ScheduledAction",
  "description": "Resource to create a Application Autoscaling Scheduled Action. Can be used with any resource that uses AWS Application Autoscaling Dimensions.",
  "sourceUrl": "https://github.com/aws-cloudformation/community-registry-extensions/",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "EndTime": {
      "type": "string"
    },
    "ResourceId": {
      "type": "string",
      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*",
      "description": "Must be a valid resource as defined in https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html#autoscaling-PutScheduledAction-request-ResourceId"
    },
    "ScalableDimension": {
      "type": "string"
    },
    "ScalableTargetAction": {
      "type": "object",
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "MaxCapacity"
          ]
        },
        {
          "required": [
            "MinCapacity"
          ]
        }
      ],
      "properties": {
        "MaxCapacity": {
          "type": "number",
          "minimum": 0
        },
        "MinCapacity": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "Schedule": {
      "type": "string",
      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*",
      "description": "Must be a valid schedule as defined in https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html#autoscaling-PutScheduledAction-request-ResourceId"
    },
    "ScheduledActionName": {
      "type": "string",
      "pattern": "(?!((^[ ]+.*)|(.*([\\u0000-\\u001f]|[\\u007f-\\u009f]|[:/|])+.*)|(.*[ ]+$))).+",
      "description": "Must be a valid action name as defined in https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html#autoscaling-PutScheduledAction-request-ResourceId"
    },
    "ServiceNamespace": {
      "type": "string"
    },
    "StartTime": {
      "type": "string"
    },
    "Timezone": {
      "type": "string",
      "default": "UTC",
      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*",
      "description": "Must be a valid timestamp as defined in https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html#autoscaling-PutScheduledAction-request-ResourceId"
    },
    "ScheduledActionARN": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "ScalableDimension",
    "ResourceId",
    "ScheduledActionName",
    "ServiceNamespace",
    "Schedule",
    "ScalableTargetAction"
  ],
  "readOnlyProperties": [
    "/properties/ScheduledActionARN"
  ],
  "primaryIdentifier": [
    "/properties/ScheduledActionARN"
  ],
  "createOnlyProperties": [
    "/properties/ScheduledActionName",
    "/properties/ResourceId",
    "/properties/ScalableDimension",
    "/properties/ServiceNamespace"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "application-autoscaling:DescribeScheduledActions",
        "application-autoscaling:PutScheduledAction"
      ]
    },
    "read": {
      "permissions": [
        "application-autoscaling:DescribeScheduledActions"
      ]
    },
    "update": {
      "permissions": [
        "application-autoscaling:DescribeScheduledActions",
        "application-autoscaling:PutScheduledAction"
      ]
    },
    "delete": {
      "permissions": [
        "application-autoscaling:DescribeScheduledActions",
        "application-autoscaling:DeleteScheduledAction"
      ]
    }
  }
}

=== aws-cloudformation/community-registry-extensions/resources/ApplicationAutoscaling_ScheduledAction/inputs/inputs_1_update.json
{
  "ScheduledActionName": "cfn-testing-resource",
  "ServiceNamespace": "dynamodb",
  "ScalableDimension": "dynamodb:table:ReadCapacityUnits",
  "ScalableTargetAction": {
    "MinCapacity": 1,
    "MaxCapacity": 1
  },
  "Schedule": "cron(10 2 ? * FRI)",
  "Timezone": "Europe/London",
  "ResourceId": "table/awscommunityscheduledactiontesttable"
}
